version: '3'
services:
  vue-ui:
    build:
      context: .
    ports:
      - "8080:80"
    container_name: psytribe-vue
    restart: unless-stopped

    volumes:
      - ./:/usr/src/psytribe
      - /usr/src/psytribe/node_modules
      - ./log/:/root/.npm/_logs/